snapshot:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: camera
          integration: ucams
    filename:
      example: "/config/www/snapshot.jpg"
      selector:
        text:

get_archive:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: camera
          integration: ucams
    start_time:
      required: true
      example: "2026-05-07 14:30:00"
      selector:
        datetime:
    duration:
      required: true
      example: "00:05:00"
      selector:
        duration:
